language: c
before_install:
  - cd 3rd_party_software/apt-get_only-update
  - sudo make install
  - cd ../..
  - sed --in-place 's/^# deb /deb /g' 3rd_party_software/APT_Software_Sources_zh_TW/Ubuntu-prerelease.list
  - sudo install -D --owner=root --group=root --mode=0644 3rd_party_software/APT_Software_Sources_zh_TW/Ubuntu-prerelease.list /etc/apt/sources.list.d
  - sudo apt-get_only-update /etc/apt/sources.list.d/Ubuntu-prerelease.list
install:
  - sudo apt-get install shellcheck
script: 
  - bash -nu Installer.sh
  - shellcheck Installer.sh
  - bash -nu Executable/mountAllSwapPartitions.sh
  - shellcheck Executable/mountAllSwapPartitions.sh
  